### ISSUE TITLE
suggested to change the title color

### ISSUE THREAD

**Issue by umaglitter** [umarajiram/git-crash-course#1]
i think title color is not effective.

i suggest you the color 

```css 
h1 { color: #ecac3f;
}
```
